Repository mulesoft/mulesoft-docs, pull requests merged in 2018-08, with the labels that each got.

#2827 [DO NOT MERGE] Update docs To Publish and Deploy Exchange
  anypoint-exchange/v/latest/to-publish-assets-maven.adoc
Labels: Do Not Merge

#3076 [CS-4608]: Add documentation for identity management support with OpenID Connect by salesforce - Merge after Aug 25th 2018
  access-management/v/latest/conf-openid-connect-task.adoc
  access-management/v/latest/external-identity.adoc
Labels: CS

#2898 Datamapper is not there in mule 3.8, replace datamapper with dataweave
  mule-user-guide/v/3.8/publishing-a-soap-api.adoc
Labels: Contributor Verified
